import { CalendarDays, CarFront, Check, ShieldCheck } from 'lucide-react'
import { PageShell } from './page-shell'

export function Bookings({ booked, onExplore }: { booked: boolean; onExplore: () => void }) {
  return <PageShell eyebrow="Tu movilidad" title="Mis reservas" description="Todo lo que necesitas para llegar, estacionar y seguir."><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-border bg-card p-5 sm:p-7">{booked ? <><div className="flex items-start justify-between"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-accent/15 px-3 py-1.5 text-xs font-medium text-accent-foreground"><Check className="size-3.5" /> Confirmada</span><h2 className="mt-5 text-2xl font-semibold tracking-[-0.05em]">Parking Las Condes</h2><p className="mt-1 text-sm text-muted-foreground">Hoy, 14:00 — 16:00 · El Golf</p></div><CarFront className="size-8 text-accent" /></div><div className="mt-7 rounded-2xl bg-muted p-5"><p className="text-xs text-muted-foreground">Código de acceso</p><p className="mt-2 font-mono text-3xl tracking-[0.2em]">A7K-29</p><p className="mt-2 text-xs text-muted-foreground">Muéstralo al llegar al estacionamiento.</p></div><div className="mt-6 grid grid-cols-2 gap-3"><button className="rounded-full border border-border px-4 py-3 text-sm font-medium">Ver indicaciones</button><button className="rounded-full bg-primary px-4 py-3 text-sm font-medium text-primary-foreground">Contactar anfitrión</button></div></> : <EmptyBookings onExplore={onExplore} />}</div><div className="rounded-3xl border border-accent/20 bg-accent/10 p-6 text-foreground"><p className="text-sm text-muted-foreground">Tu actividad</p><h3 className="mt-3 text-2xl font-semibold tracking-[-0.05em]">Reserva con confianza.</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/65">Cada espacio tiene un anfitrión verificado y detalles claros antes de confirmar.</p><div className="mt-8 flex items-center gap-3 border-t border-border pt-5 text-sm"><ShieldCheck className="size-5 text-accent" /> Pagos y datos protegidos</div></div></div></PageShell>
}

function EmptyBookings({ onExplore }: { onExplore: () => void }) {
  return <div className="flex min-h-64 flex-col items-center justify-center text-center"><CalendarDays className="size-10 text-accent" /><h2 className="mt-4 text-xl font-semibold">Aún no tienes reservas</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">Encuentra un lugar cerca de tu destino y déjalo listo para cuando llegues.</p><button onClick={onExplore} className="mt-5 rounded-full bg-primary px-5 py-3 text-sm font-medium text-primary-foreground">Explorar estacionamientos</button></div>
}
