'use client'

import { CalendarDays, CarFront, Clock3, LockKeyhole, Menu, Plus, Search, ShieldCheck, Star, UserRound, X } from 'lucide-react'
import type { ReactNode } from 'react'
import type { Spot, View } from '@/lib/estacionando/types'

type SiteChromeProps = { view: View; nav: (view: View) => void; selected: Spot | null; closeSpot: () => void; reserve: () => void; children: ReactNode }

export function SiteChrome({ view, nav, selected, closeSpot, reserve, children }: SiteChromeProps) {
  return <>
    <header className="sticky top-0 z-20 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-10"><button onClick={() => nav('explore')} className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><CarFront className="size-5" /></span><span className="text-lg font-semibold tracking-[-0.04em]">estacionando<span className="text-accent">.</span></span></button><nav className="hidden items-center gap-1 text-sm md:flex">{([['explore', 'Explorar'], ['bookings', 'Mis reservas'], ['publish', 'Publicar espacio'], ['profile', 'Perfil']] as const).map(([key, label]) => <button key={key} onClick={() => nav(key)} className={`rounded-full px-4 py-2 transition ${view === key ? 'bg-muted font-medium text-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{label}</button>)}</nav><div className="flex items-center gap-2"><button onClick={() => nav('profile')} className="flex items-center gap-2 rounded-full border border-border px-3 py-2 text-sm font-medium hover:bg-muted"><UserRound className="size-4" /><span className="hidden sm:inline">Lorenzo</span></button><button aria-label="Abrir menú" className="rounded-full border border-border p-2.5 md:hidden"><Menu className="size-4" /></button></div></div></header>
    {children}
    <MobileNav view={view} nav={nav} />
    {selected && <SpotDialog spot={selected} close={closeSpot} reserve={reserve} />}
    <SiteFooter />
  </>
}

function MobileNav({ view, nav }: Pick<SiteChromeProps, 'view' | 'nav'>) { return <div className="fixed bottom-4 left-1/2 z-10 flex -translate-x-1/2 items-center gap-1 rounded-full border border-border bg-card/95 p-1.5 shadow-xl backdrop-blur md:hidden">{([['explore', Search], ['bookings', CalendarDays], ['publish', Plus], ['profile', UserRound]] as const).map(([key, Icon]) => <button key={key} aria-label={key} onClick={() => nav(key)} className={`rounded-full p-3 ${view === key ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}><Icon className="size-4" /></button>)}</div> }

function SpotDialog({ spot, close, reserve }: { spot: Spot; close: () => void; reserve: () => void }) { return <div className="fixed inset-0 z-30 flex items-end justify-center bg-primary/30 p-4 backdrop-blur-sm sm:items-center" onClick={close}><div role="dialog" aria-modal="true" className="w-full max-w-lg overflow-hidden rounded-3xl bg-background shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="relative h-52"><img src={spot.image} alt={spot.title} className="size-full object-cover" /><button aria-label="Cerrar" onClick={close} className="absolute right-4 top-4 rounded-full bg-background/90 p-2"><X className="size-4" /></button></div><div className="p-6"><div className="flex justify-between"><div><h2 className="text-2xl font-semibold tracking-[-0.05em]">{spot.title}</h2><p className="mt-1 text-sm text-muted-foreground">{spot.area}</p></div><span className="flex gap-1 text-sm"><Star className="size-4 fill-accent text-accent" />{spot.rating}</span></div><div className="my-5 grid grid-cols-3 border-y border-border py-4 text-center text-xs"><span><ShieldCheck className="mx-auto mb-1 size-4 text-accent" />Verificado</span><span><Clock3 className="mx-auto mb-1 size-4 text-accent" />24/7</span><span><LockKeyhole className="mx-auto mb-1 size-4 text-accent" />Privado</span></div><div className="flex items-center justify-between"><p><strong className="text-xl">${spot.price.toLocaleString('es-CL')}</strong> <span className="text-sm text-muted-foreground">/ hora</span></p><button onClick={reserve} className="rounded-full bg-accent px-5 py-3 text-sm font-semibold text-accent-foreground">Reservar lugar</button></div></div></div></div> }

function SiteFooter() { return <footer className="border-t border-border bg-background"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 lg:grid-cols-[1.3fr_2fr] lg:px-10 lg:py-16"><div><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-accent text-accent-foreground"><CarFront className="size-5" /></span><span className="text-lg font-semibold tracking-[-0.04em]">estacionando<span className="text-accent">.</span></span></div><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">La forma más simple de encontrar y compartir un lugar para estacionar.</p><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-border bg-muted px-3 py-1.5 text-xs text-muted-foreground"><ShieldCheck className="size-3.5 text-accent" /> Comunidad verificada</div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{[['Descubre', 'Explorar lugares', 'Cómo funciona', 'Preguntas frecuentes'], ['Comparte', 'Publicar espacio', 'Guía de anfitriones', 'Centro de ayuda'], ['Estacionando', 'Sobre nosotros', 'Privacidad', 'Contacto']].map(([title, ...links]) => <div key={title}><p className="text-sm font-semibold">{title}</p><div className="mt-4 flex flex-col gap-3 text-sm text-muted-foreground">{links.map((link) => <button key={link} className="text-left hover:text-foreground">{link}</button>)}</div></div>)}</div></div></footer> }
