spring.application.name=backend

# Conexión a Supabase
spring.datasource.url=jdbc:postgresql://db.wuozftmanlbvexmyaqqj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=fGcDNk7K7v36fNUn
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect